name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install backend dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Run backend tests
      run: |
        . venv/bin/activate
        pytest

    - name: Lint backend code
      run: |
        . venv/bin/activate
        flake8 .

    - name: Build frontend with Bootstrap
      run: |
        # Bootstrap CSS herunterladen und in das statische Verzeichnis kopieren
        mkdir -p static/css
        curl -L https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css -o static/css/bootstrap.min.css
